version: '3.8'

services:
  estima:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estima-app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
